### ISSUE TITLE
Testing GitHub feature

### ISSUE THREAD

**Issue by MaorMutzafi** [galeoai/ctypi#1]
What does the brackets (`[N:-N,N:-N]`) in the following line do?
`diff_frame_dx = conv2((moving-ref),x_spectral_filter)[N:-N,N:-N]`

**Comment by ordicker** [comment]
syntax wise that's slicing, in Matlab that's stam_matrix(N:end-N,N:end-N). 
functionality wise that's for 'valid' convolution.

Hope that helps, if not reopen the issue.

**Comment by MaorMutzafi** [comment]
סתם שתדע N צריך להיות אורך הפילטר חצי פחות חצי. כי האורך אי זוגי. ואז
הגבולות בין N+1:end-N

בתאריך יום א׳, 22 בנוב׳ 2020, 8:53, מאת Or Dicker ‏<notifications@github.com

**Comment by ordicker** [comment]
נקודה מעולה. 

רוצה לעשות את התיקון בעצמך?
זה נראה לי תרגיל טוב

אתה צריך לעשות pull request

אור.

**Comment by MaorMutzafi** [comment]
לא ידעתי שמה ששלחתי במייל נכנס לשרשור הזה
